services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
